swagger: '2.0'
info:
  version: '0.0.1'
  title: Preference public API
  description: Preference public API
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: localhost:4000
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /movies:
    get:
      description: Get movies list
      summary: Get movies list
      tags:
      - movie
      operationId: MoviesGet
      produces:
      - application/json
      parameters:
        - in: query
          name: sortBy
          schema:
            type: string
          description: Field to sort by
        - in: query
          name: sortOrder
          schema:
            type: string
          description: Value to define sort direction - 'decs' or 'asc'
        - in: query
          name: search
          schema:
            type: string
          description: String to search by title
        - in: query
          name: filter
          schema:
            type: array
            items:
              type: string
          description: Array to filter by genres
      responses:
        200:
          description: Movies list
          schema:
            type: array
            items:
              $ref: '#/definitions/Movie'
          examples: {}
  /movies/{id}:
    get:
      description: Get movie by id
      summary: Get movie by id
      tags:
      - movie
      operationId: MoviesGetById
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: string
        description: ''
      responses:
        200:
          description: Movie object
          schema:
            $ref: '#/definitions/Movie'
          examples: {}

definitions:
  Movie:
    title: Movie
    type: object
    properties:
      id:
        type: number
      title:
        description: Movie title
        type: string
      tagline:
        type: string
      vote_average:
        type: number
      vote_count:
        type: number
      release_date:
        type: string
      poster_path:
        description: Poster Image
        type: string
      overview:
        type: string
        description: Short description of movie
      budget:
        type: number
      revenue:
        type: number
      genres:
        type: array
        items:
          type: string
